# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5989cd12df5a21b872c6d124c3915387b8c11f28a2e177b1c05fa3ab2b95082dbcb70c90407d5bb2e76d281a121443502ca2401c7156ac13fc1d17780534d04b

test:
  secret_key_base: 4b166d569e694663c1e0c39b4d2fd4d7b918a6619535adc92cba0835527d52fa200e369fb6f7012e3901dc66f0e910269f2693f8d41515caca84178541eaff2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
